// flow-typed signature: ae26f309789870cc8b947cda0182a4d3
// flow-typed version: <<STUB>>/compression_vexpressjs/compression#pull/155/head/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compression'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'compression' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'compression/test/compression' {
  declare module.exports: any;
}

// Filename aliases
declare module 'compression/index' {
  declare module.exports: $Exports<'compression'>;
}
declare module 'compression/index.js' {
  declare module.exports: $Exports<'compression'>;
}
declare module 'compression/test/compression.js' {
  declare module.exports: $Exports<'compression/test/compression'>;
}
