// flow-typed signature: 3cd1ba173d8e987bea03a6e88be6aaea
// flow-typed version: <<STUB>>/eslint-config-cumul8_v7.0.8/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-cumul8'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-cumul8' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-cumul8/bin/eslint-cumul8' {
  declare module.exports: any;
}

declare module 'eslint-config-cumul8/foo' {
  declare module.exports: any;
}

declare module 'eslint-config-cumul8/foo.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-cumul8/bin/eslint-cumul8.js' {
  declare module.exports: $Exports<'eslint-config-cumul8/bin/eslint-cumul8'>;
}
declare module 'eslint-config-cumul8/foo.js' {
  declare module.exports: $Exports<'eslint-config-cumul8/foo'>;
}
declare module 'eslint-config-cumul8/foo.test.js' {
  declare module.exports: $Exports<'eslint-config-cumul8/foo.test'>;
}
declare module 'eslint-config-cumul8/index' {
  declare module.exports: $Exports<'eslint-config-cumul8'>;
}
declare module 'eslint-config-cumul8/index.js' {
  declare module.exports: $Exports<'eslint-config-cumul8'>;
}
