// flow-typed signature: ab3fb4f02ea45b5e750767a1d56f891f
// flow-typed version: <<STUB>>/greenlock-express_v2.7.18/flow_v0.116.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'greenlock-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'greenlock-express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'greenlock-express/lib/compat' {
  declare module.exports: any;
}

// Filename aliases
declare module 'greenlock-express/index' {
  declare module.exports: $Exports<'greenlock-express'>;
}
declare module 'greenlock-express/index.js' {
  declare module.exports: $Exports<'greenlock-express'>;
}
declare module 'greenlock-express/lib/compat.js' {
  declare module.exports: $Exports<'greenlock-express/lib/compat'>;
}
