// flow-typed signature: e570017fd763f6606db86aeceb83b7b7
// flow-typed version: <<STUB>>/greenlock-express_v2.3.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'greenlock-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'greenlock-express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'greenlock-express/index' {
  declare module.exports: $Exports<'greenlock-express'>;
}
declare module 'greenlock-express/index.js' {
  declare module.exports: $Exports<'greenlock-express'>;
}
