// flow-typed signature: 759dfd5d19e5715ec18895fcff96a574
// flow-typed version: <<STUB>>/greenlock-store-fs_v3.0.2/flow_v0.116.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'greenlock-store-fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'greenlock-store-fs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'greenlock-store-fs/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'greenlock-store-fs/index' {
  declare module.exports: $Exports<'greenlock-store-fs'>;
}
declare module 'greenlock-store-fs/index.js' {
  declare module.exports: $Exports<'greenlock-store-fs'>;
}
declare module 'greenlock-store-fs/test.js' {
  declare module.exports: $Exports<'greenlock-store-fs/test'>;
}
