// flow-typed signature: c1536b61de9b206458e1566edea713e1
// flow-typed version: <<STUB>>/greenlock-express_v2.1.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'greenlock-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'greenlock-express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'greenlock-express/examples/force-renew' {
  declare module.exports: any;
}

declare module 'greenlock-express/examples/simple' {
  declare module.exports: any;
}

declare module 'greenlock-express/lex' {
  declare module.exports: any;
}

// Filename aliases
declare module 'greenlock-express/examples/force-renew.js' {
  declare module.exports: $Exports<'greenlock-express/examples/force-renew'>;
}
declare module 'greenlock-express/examples/simple.js' {
  declare module.exports: $Exports<'greenlock-express/examples/simple'>;
}
declare module 'greenlock-express/lex.js' {
  declare module.exports: $Exports<'greenlock-express/lex'>;
}
