// flow-typed signature: fe6eaa26588b467025000c6d8e1b0696
// flow-typed version: <<STUB>>/react-tippy_v1.2.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tippy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tippy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-tippy/dist/react-tippy' {
  declare module.exports: any;
}

declare module 'react-tippy/webpacklib.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-tippy/dist/react-tippy.js' {
  declare module.exports: $Exports<'react-tippy/dist/react-tippy'>;
}
declare module 'react-tippy/webpacklib.config.js' {
  declare module.exports: $Exports<'react-tippy/webpacklib.config'>;
}
