// flow-typed signature: a191cfe0566da73a7189d6c460957e89
// flow-typed version: <<STUB>>/react-tippy_v1.3.1/flow_v0.110.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tippy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tippy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-tippy/dist/react-tippy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-tippy/dist/react-tippy.js' {
  declare module.exports: $Exports<'react-tippy/dist/react-tippy'>;
}
