// flow-typed signature: 805a7e3888447a71d8b87fd1a2d5db6d
// flow-typed version: <<STUB>>/react-helmet_v6.0.0-beta/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-helmet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-helmet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-helmet/es/Helmet' {
  declare module.exports: any;
}

declare module 'react-helmet/lib/Helmet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-helmet/es/Helmet.js' {
  declare module.exports: $Exports<'react-helmet/es/Helmet'>;
}
declare module 'react-helmet/lib/Helmet.js' {
  declare module.exports: $Exports<'react-helmet/lib/Helmet'>;
}
