// flow-typed signature: 051641322bc3bd4feff98dfcaaa92993
// flow-typed version: <<STUB>>/redirect-https_v1.3.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redirect-https'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redirect-https' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redirect-https/example' {
  declare module.exports: any;
}

declare module 'redirect-https/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redirect-https/example.js' {
  declare module.exports: $Exports<'redirect-https/example'>;
}
declare module 'redirect-https/index' {
  declare module.exports: $Exports<'redirect-https'>;
}
declare module 'redirect-https/index.js' {
  declare module.exports: $Exports<'redirect-https'>;
}
declare module 'redirect-https/test.js' {
  declare module.exports: $Exports<'redirect-https/test'>;
}
