// flow-typed signature: 048d4fe4c5706a52c2abc1aa477eb72f
// flow-typed version: <<STUB>>/@globexdesigns/deploy_v0.3.12/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@globexdesigns/deploy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@globexdesigns/deploy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@globexdesigns/deploy/bin/Deploy' {
  declare module.exports: any;
}

declare module '@globexdesigns/deploy/bin/index' {
  declare module.exports: any;
}

declare module '@globexdesigns/deploy/bin/types/config' {
  declare module.exports: any;
}

declare module '@globexdesigns/deploy/bin/utils/local' {
  declare module.exports: any;
}

declare module '@globexdesigns/deploy/bin/utils/server' {
  declare module.exports: any;
}

// Filename aliases
declare module '@globexdesigns/deploy/bin/Deploy.js' {
  declare module.exports: $Exports<'@globexdesigns/deploy/bin/Deploy'>;
}
declare module '@globexdesigns/deploy/bin/index.js' {
  declare module.exports: $Exports<'@globexdesigns/deploy/bin/index'>;
}
declare module '@globexdesigns/deploy/bin/types/config.js' {
  declare module.exports: $Exports<'@globexdesigns/deploy/bin/types/config'>;
}
declare module '@globexdesigns/deploy/bin/utils/local.js' {
  declare module.exports: $Exports<'@globexdesigns/deploy/bin/utils/local'>;
}
declare module '@globexdesigns/deploy/bin/utils/server.js' {
  declare module.exports: $Exports<'@globexdesigns/deploy/bin/utils/server'>;
}
