// flow-typed signature: eab7c745b71bf2cf4187c9bf4a746077
// flow-typed version: <<STUB>>/@globexdesigns/deploy_v0.2.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@globexdesigns/deploy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@globexdesigns/deploy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@globexdesigns/deploy/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@globexdesigns/deploy/src/index.js' {
  declare module.exports: $Exports<'@globexdesigns/deploy/src/index'>;
}
