name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      env:
        ROCKETRY_PW: ${{ secrets.ROCKETRY_PW }}
      run: |
        yarn deploy
